#! /bin/sh

# Settings for building Ubuntu CD images.  The build procedure also involves
# syncing a local Ubuntu mirror; see etc/anonftpsync for settings affecting what
# is mirrored and where.

. "$CDIMAGE_ROOT/bin/functions.sh"

if [ "$DEBUG" ] && [ "$DEBUG" -gt 1 ]; then
	set -x
fi

export LC_ALL=C

PROJECT="${PROJECT:-ubuntu}"
CAPPROJECT="${CAPPROJECT:-Ubuntu}"
export ALL_DISTS="${ALL_DISTS:-warty hoary breezy dapper edgy feisty gutsy hardy intrepid jaunty karmic lucid maverick natty oneiric}"
DIST="${DIST:-oneiric}"

# If you want to build image for one or more architectures comment out the
# following line
#ARCHES=i386

# All projects currently being built.  This is used for building source
# images.  Note that we only need to include projects with their own seed
# collections, so not ubuntu-server.
ALL_PROJECTS="${ALL_PROJECTS:-ubuntu kubuntu kubuntu-mobile edubuntu xubuntu ubuntustudio mythbuntu}"

if [ -z "$ARCHES" ]; then
	ARCHES="$(default-arches "$PROJECT" "$IMAGE_TYPE" "$DIST")"
fi
CPUARCHES="$(echo "$ARCHES" | xargs -n1 | sed 's/+.*//' | sort -u | xargs)"

GNUPG_DIR="$CDIMAGE_ROOT/secret/dot-gnupg"
SIGNING_KEYID=FBB75451

BRITNEY="$CDIMAGE_ROOT/britney"

#export LOCAL_SEEDS=file:///path/to/local_seeds

# Do not update the local mirror
#export CDIMAGE_NOSYNC=1 

# Create alternate iso
#export CDIMAGE_INSTALL=1

# Do not create source iso
if [ -z "$CDIMAGE_ONLYSOURCE" ]; then
	export CDIMAGE_NOSOURCE=1
fi

# Create desktop iso
#export CDIMAGE_LIVE=1

# Hosts that need to be notified when the build is done.  Third-party users
# will want to keep this variable empty.
# The "async" mirrors will be notified asynchronously, i.e. we won't wait for
# them to respond.
TRIGGER_MIRRORS=
TRIGGER_MIRRORS_ASYNC=

export TRIGGER_MIRRORS
export TRIGGER_MIRRORS_ASYNC

# Some older versions of debootstrap must *think* they're running as root,
# even though that's not really needed here.  If you have that problem, make
# sure you have fakeroot installed and uncomment this variable.
DEBOOTSTRAPROOT=fakeroot
export DEBOOTSTRAPROOT

PATH="$CDIMAGE_ROOT/bin:$PATH"
export PATH

umask 002
